site_name: Wizkers Documentation
google_analytics: ['UA-66729721-2', 'auto']
pages:
- Overview: index.md
- Users: userdoc.md
- Developers:
    - Overview: devdoc.md
    - Building: building.md
    - Connections: dev/connections.md
    - Instruments: dev/instruments.md
    - Outputs: dev/outputs.md
    - Debugging: dev/debugging.md
    - API Access: dev/api.md
- Instruments:
    - Medcom Onyx: ins/medcom-onyx.md
    - Medcom Blue Onyx: ins/medcom-onyx-ble.md
#    - Medcom GeigerLink: ins/medcom-geigerlink.md
    - Fried Circuits OLED backpack: ins/fcoled.md
    - Sark 110: ins/sark110.md
    - Elecraft KX3: ins/elecraft-kx3.md
    - Elecraft Remote KX3: ins/elecraft-remote-kx3.md
    - Fluke 287/289 DMMs: ins/fluke289.md
    - Simple serial terminal: ins/simple-serial.md
- Outputs:
    - REST API: out/rest.md
    - Safecast: out/safecast.md
    - rigctld:  out/rigctld.md
    - WebRTC:   out/webrtc.md