site_name: Wizkers Documentation
pages:
- Overview: index.md
- Users: userdoc.md
- Developers:
    - Overview: devdoc.md
    - Building: building.md
    - Creating outputs: dev/outputs.md
    - Creating instruments: dev/instruments.md
    - Connections: dev/connections.md
    - Debugging: dev/debugging.md
- Instruments:
    - Medcom Onyx: ins/medcom-onyx.md
    - Medcom Blue Onyx: ins/medcom-onyx-ble.md
    - Medcom GeigerLink: ins/medcom-geigerlink.md
    - Fried Circuits OLED backpack: ins/fcoled.md
    - Sark 110: ins/sark110.md
    - Elecraft KX3: ins/elecraft-kx3.md
    - Elecraft Remote KX3: ins/elecraft-remote-kx3.md
- Outputs:
    - REST API: out/rest.md
    - Safecast: out/safecast.md
    - rigctld:  out/rigctld.md
    - WebRTC:   out/webrtc.md